application: disce
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /resources/www/ventus/stylesheets/

  static_dir: resources/www/ventus/stylesheets

- url: /resources/www/ventus/build/

  static_dir: resources/www/ventus/build

- url: /resources/www/ventus/vendor/

  static_dir: resources/www/ventus/vendor
  
- url: /resources/www/ventus/img/

  static_dir: resources/www/ventus/img

- url: /.*
  script: Disce.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: Wornik
  version: latest
